# LING 573 Question Answering System
# Code last updated 4/17/14 by Clara Gordon
# This code implements an InfoRetriever for the question answering system.


from pymur import *

class InfoRetriever():

    # builds a QueryEnvironment associated with the indexed document collection
    def __init__(self, queries, index_env):
        # how to get this to link up to the doc collection?
        self.query_env = QueryEnvironment()

    # creates a list of all the snippets returned by all the queries generated by
    # the query-processing module
    def search_passages(self, queries):
        results = []
        for query in queries:
            # second argument is the number of documents desired
            query_results = self.query_env.runQuery(query, 10)
             # still not sure how to extract actual passages...
            results.append(query_results)

        return results


