# LING 573 Question Answering System
# Code last updated 4/17/14 by Clara Gordon
# This code implements an InfoRetriever for the question answering system.


from pymur import *
from general_classes import *


class InfoRetriever:

    # builds a QueryEnvironment associated with the indexed document collection
    def __init__(self, queries, index_env):
        # how to get this to link up to the doc collection?
        self.query_env = QueryEnvironment()
        self.query_env.addIndex("/home2/cjaja/classwork/spring-2014/ling573/question-answering/src/index2/")



    # creates a list of all the passages returned by all the queries generated by
    # the query-processing module
    def retrieve_passages(self, queries):
        results = []
        for query in queries:
            # second argument is the number of documents desired
            query_results = self.query_env.runQuery(query, 10)
            for result in query_results:
                idx = result.document
                begin = result.begin
                end = result.end
                doc = self.query_env.documents([idx])
                passage = Passage(doc.text[begin:end], result.score)
                results.append(passage)

        return results


